version: "3.8"

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - odoo-net
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - odoo-net

  odoo:
    container_name: odoo
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./film_management/odoo.conf:/etc/odoo/odoo.conf
      - ./film_management/addons:/mnt/extra-addons
      - ./logs/odoo:/var/log/odoo
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_PASSWORD=${ODOO_ADMIN_PASSWORD}
      - MOVIE_API_URL=${MOVIE_API_URL}
      - MOVIE_API_KEY=${MOVIE_API_KEY}
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"]
    networks:
      - odoo-net
    env_file:
      - .env

volumes:
  db-data:

networks:
  odoo-net:
    driver: bridge
